config/routes.rb
Sallyport2::Application.routes.draw do
  
  devise_for :members

   root :to => 'homes#index'
   get :contact_us, :to => 'homes#contact_us'
   get :help, :to => 'homes#help'
   get :useful_links, :to => 'homes#useful_links'
   post :send_message, :to => 'homes#send_message'

   resources :dances, :only => [:index, :show]

   resources :services, :only => [] do
     collection do
       get   :new_ip
       post  :set_ip
       get   :tvheadend
     end
   end

   namespace :admin do
   	resources :blurbs, :except => :show

   end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/dances_controller.rb
class DancesController < ApplicationController

def index
 @dances = Blurb.where(:cat => 'dance')
 @dance = @dances.where("name like '%Newbiggin%'").first
end


def show
 @dance = Blurb.where(:cat => 'dance').find(params[:id])
 respond_to do |format|
 	format.js
 end
end


end

app/views/dances/_dance.html.erb
<div class="col-md-12">
	<h3><%=@dance.name%></h3>
	<hr/>
	<div class="dance-content">
	  <%= simple_format(@dance.content) %>
	</div>
</div>

app/views/dances/index.html.erb
<div class="row">
<div class='col-md-12'>

<div class="btn-group" role="group" >  
<% @dances.each do |dance| %>
<%= link_to dance.name.gsub("\s",'&nbsp;').html_safe, dance_path(dance), :class => "btn btn-sm btn-inverse", :remote => true %>
<% end %>

</div>

<div class="row" id="dance-text">
	<h2>The Dances</h2>
	<%= render :partial => 'dances/dance' %>
</div>
</div>

app/views/dances/show.js.erb
$('#dance-text').html("<%= escape_javascript(render :partial => 'dances/dance') %>");