config/routes.rb
Sallyport2::Application.routes.draw do
  
  devise_for :members

   root :to => 'homes#index'
   get :contact_us, :to => 'homes#contact_us'
   get :help, :to => 'homes#help'
   get :useful_links, :to => 'homes#useful_links'
   post :send_message, :to => 'homes#send_message'

   resources :dances, :only => [:index, :show]

   resources :services, :only => [] do
     collection do
       get   :new_ip
       post  :set_ip
       get   :tvheadend
     end
   end

   namespace :admin do
   	resources :blurbs, :except => :show

   end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/blurb.rb
class Blurb < ActiveRecord::Base
	after_save :parse_practices

  validates  :name, :content, :presence => true

	def unfold_for_links
		self.content.split("\r\n").map{|l| l.split("#")}
	end

	private

	def parse_practices
		return unless self.name == 'practices'
		  Practice.destroy_future!
      parser = PracticeParser.new
      parser.parse
	end

end

app/controllers/admin/blurbs_controller.rb
class Admin::BlurbsController < Admin::ApplicationController

	before_filter :find_blurb, :except => [:index, :new, :create]

	def index
		@blurbs = Blurb.order(:cat, :id)
	end

	
	def new
     @blurb = Blurb.new

	end

	def create
      @blurb = Blurb.create(blurb_params)
      if @blurb.save
      	redirect_to admin_blurbs_path, notice: "Successfully created new blurb"
      else
      	render :new
      end
	end

	def edit

	end

	def update
	  @blurb.update_attributes(blurb_params)
      if @blurb.save
      	redirect_to admin_blurbs_path, notice: "Successfully updated blurb"
      else
      	render :edit
      end

	end


	def destroy
	  if @blurb.destroy
      	redirect_to admin_blurbs_path, :notice => "Successfully deleted blurb"
      else
      	redirect_to admin_blurbs_path, :notice => "Sorry failed to delete because: #{@blurb.errors.full_messages.to_sentence}"
      end

	end


	def find_blurb
		@blurb = Blurb.find params[:id]
	end

    private 

    def blurb_params
       params.require(:blurb).permit(:name, :cat, :content)
    end

end

app/views/admin/blurbs/_errors.html.erb
<div class="blurb-errors">
  <h3><%= object.errors.size %> Error(s) prevented saving this:</h3>
  <%= object.errors.full_messages.to_sentence %>
</div>

app/views/admin/blurbs/_form.html.erb
<%= form_for [:admin, @blurb] do |f| %>
 <% if @blurb.errors.any? %>
        <%= render 'errors', object: @blurb %>
 <% end %>
<%= form_fields(f, "Name", :name, f.object.name) %>
<%= form_fields(f, "cat", :cat, f.object.cat) %>
<div class='form-group width-maxed'>
	<%= f.label "Content"  %>

	  <%= f.text_area :content, :rows => 8, :class => 'form-control'  %>
</div>
<div class='form-group width-maxed'>
	<%= f.label " "  %>   
	<%= f.submit "Submit", class: 'btn btn-inverse pull-right'  %>	
</div>
	
     


<% end %>

app/views/admin/blurbs/edit.html.erb
<h1>Edit Blurb</h1>

<%= render :partial => 'form' %>

app/views/admin/blurbs/index.html.erb
<h1>Blurbs</h1>

<table class="table">
<thead>
<tr>
<th>Name</th><th>Category</th><th>Content</th>
</tr>
</thead>
<tbody>
 <% @blurbs.each do |blurb| %>
 	<tr>
 		<td><%= link_to blurb.name.split(" ").join("<br/>").html_safe, edit_admin_blurb_path(blurb), :class => "btn btn-inverse btn-sm", :style =>"width:80px;" %></td>
 		<td><%= blurb.cat %></td>
 		<td><%= blurb.content.truncate 100 %></td>
 	</tr>

 <% end %>
</tbody>

</table>

app/views/admin/blurbs/new.html.erb
<h2>New Blurb</h2>
<%= render :partial => 'form' %>