config/routes.rb
Sallyport2::Application.routes.draw do
  
  devise_for :members

   root :to => 'homes#index'
   get :contact_us, :to => 'homes#contact_us'
   get :help, :to => 'homes#help'
   get :useful_links, :to => 'homes#useful_links'
   post :send_message, :to => 'homes#send_message'

   resources :dances, :only => [:index, :show]

   resources :services, :only => [] do
     collection do
       get   :new_ip
       post  :set_ip
       get   :tvheadend
     end
   end

   namespace :admin do
   	resources :blurbs, :except => :show

   end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/homes_controller.rb
#encoding: utf-8
class HomesController < ApplicationController

def index
  @intro= Blurb.find_by_name('Homepage')
end

def contact_us
  session[:start_time] = Time.now
end

def help
 @blurb = Blurb.find_by_name("Help for Visitors")
end

def useful_links
  @blurb = Blurb.find_by_name ("sites")
end



def send_message
  if session[:start_time] > (Time.now - 15.seconds)
    flash[:error] = "Sorry I do not believe you are human, no message sent"
    session[:start_time] = nil
    redirect_to '/' and return
  end
	message = Hashie::Mash.new(params[:message])
 	AdminMailer.contact_admin(message).deliver
	flash[:success] = "Your message has been sent to our admin members, you can expect a reply within a day"
  redirect_to '/'
end





end

app/views/homes/contact_us.html.erb
<div class="col-md-8">
<h1>Contact Us</h1>


<%= form_for :message, :url => send_message_path, :class => 'form-horizontal' do |f| %>
<div class='form-group'>
 <%= f.label "Your Name" %>
 
 <%= f.text_field :name, :class => "form-control" %>

</div>
 <div class='form-group'>
 <%= f.label "Your Email Address" %>
 
 <%= f.text_field :email, :class => "form-control" %>
</div>

<div class='form-group'>
 <%= f.label "Your Phone Number" %>
 
 <%= f.text_field :phone, :class => "form-control" %>

<div class='form-group'>
 <%= f.label "What it is about" %>
 
 <%= f.text_field :subject, :class => "form-control" %>
</div>

<div class='form-group'>
 <%= f.label "Your Message", :class =>'form-label' %>
 
 <%= f.text_area :text, :rows => 6, :style=>"width:100%;" %>
</div>

 
 <%= f.submit "Send", :class => 'btn btn-inverse' %>
</div>
<% end %>
</div>
<div class="col-md-4">
<p>Please fill in the form and submit or just phone Vince!</p>
<%= image_tag 'vincephone.png', :class => 'img img-responsive' %>
</div>
</div>

app/views/homes/help.html.erb
<h1>Help</h1>

<%= simple_format @blurb.content %>

app/views/homes/index.html.erb
<section class="row">
	<div class='col-md-12'>
	   <h2>Sallyport Sword Dancers</h2>
	</div>
</section>
<section class='row'>
    <div class="col-md-12" >
	    <ul class="rslides" style='padding:0px;'>
	      <li><img src="http://sallyport.s3.amazonaws.com/images/morpeth.jpg" alt="" style="width:100%;"></li>
	      <li><img src="http://sallyport.s3.amazonaws.com/images/Pithead.jpg" alt="" style="width:100%;"></li>
	      <li><img src="http://sallyport.s3.amazonaws.com/images/Tanfield gates.JPG" alt="" style="width:100%;"></li>
	    </ul>
    </div>
</section>

<section class="row" style='margin-top:20px;'>
<div class='col-md-12'>
	
		<%= simple_format @intro.content %>
	
</div>
</section>

        

app/views/homes/useful_links.html.erb
<h1>Rapper Resources</h1>

<ul class='sites'>
	<% @blurb.unfold_for_links.each do |site| %>
		<li><%= link_to site[0], site[1] , target: '_blank', :class => 'btn btn-inverse', :style => "margin-bottom:10px;" %></li>

	<% end %>

</ul>	