config/routes.rb
Sallyport2::Application.routes.draw do
  
  devise_for :members

   root :to => 'homes#index'
   get :contact_us, :to => 'homes#contact_us'
   get :help, :to => 'homes#help'
   get :useful_links, :to => 'homes#useful_links'
   post :send_message, :to => 'homes#send_message'

   resources :dances, :only => [:index, :show]

   resources :services, :only => [] do
     collection do
       get   :new_ip
       post  :set_ip
       get   :tvheadend
     end
   end

   namespace :admin do
   	resources :blurbs, :except => :show

   end


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sallyport Sword Dancers</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-default navbar-inverse">
        
            <div class="container-fluid"> 
            <div class="col-md-8">
                <div class='navbar-header'>
                  <a class="navbar-brand" href="/">Sallyport</a>             
                </div>
                
                  <ul class="nav nav-pills">              
                    <li><%= link_to "Dances", dances_path %></li>
                    <li><%= link_to "Contact Us", contact_us_path %></li>          
                    <li><%= link_to "Links", useful_links_path %></li>
                    <li><%= link_to "Help", help_path %></li>
                  <% if member_signed_in? && current_member.is_admin? %>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                          Admin <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                           <li><%= link_to 'Blurbs', admin_blurbs_path %></li>
                        </ul>
                      </li>
                        
                    </li>
                 
                    <% end %>
                  </ul>
              </div>
              <div class="col-md-4">
                <% if member_signed_in? %>
                  <%= link_to (current_member.fname + ': log out'), destroy_member_session_path, method: :delete , :class => 'btn navbar-btn pull-right' %>
                  <% else %>
                  <%= link_to 'login', new_member_session_path, :class => 'btn navbar-btn btn-inverse  pull-right'  %>
                <% end %>
              </div>
              
                            
            </div>
    </div>  

  <div class="container" >

        <% flash.each do |key, value| %>
           <% key = 'info' if key  == 'notice' %>
          <%= content_tag(:div, value, :class => "alert alert-#{key}") %>
        <% end %>
        <% if @practice %>
            <div class="row" id='next-practice'>
              <%== next_practice @practice %>
            </div>
        <% end %>
    <div class="row">
      <div class="col-md-2", style="text-align:center;">
        <%= image_tag 'logo.png', :style=> 'margin-left:23px;margin-top:-7px;' %>
      </div>
      <div class="col-md-10" id="main">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>